### ISSUE TITLE
`|> size()[1]`

### ISSUE THREAD

**Issue by jariji** [JuliaAPlavin/DataPipes.jl#11]
```jl
using DataPipes
julia> @p rand(4) |> size()[1]
ERROR: MethodError: no method matching size()
```

I expected that to be like `size(__)[1]`.

**Comment by aplavin** [comment]
What's the proposed logic exactly?
Currently, it adds `__` (previous value of the pipeline) whenever the step is a function call. Simple to grasp! In more complicated situations, one can just use `__` explicitly.

Anyway, curious if you have a consistent auto-`__` rule proposal that would be an improvement.
