### ISSUE TITLE
`@time` on each stage

### ISSUE THREAD

**Issue by jariji** [JuliaAPlavin/DataPipes.jl#12]
This works
```jl
julia>  @p begin
            1
            @time abs(__)
            @time sqrt(__)
        end
  0.000005 seconds
  0.000003 seconds (1 allocation: 16 bytes)
1.0
```
But I don't understand this
```jl
julia>  @p begin
            1
            @time abs
            @time sqrt
        end
  0.000001 seconds
  0.000000 seconds
sqrt (generic function with 48 methods)


```

**Comment by aplavin** [comment]
What exactly did you expect with macros? No matter if inner macros are expanded before or after `@p` does other transformations, I don't see how one would get a reasonable result with `@time`.

**Comment by jariji** [comment]
I was imagining `@time abs` expanded to `@time abs(__)` which seems to work already.

**Comment by aplavin** [comment]
`@p` operates on top-level of each step, and the top-level call it sees is the `@time` macro – not `abs` function. Aside from hardcoding a list of macros to descend into arguments, not sure if there are realistic improvements to be done here – just use `__` :)
