### ISSUE TITLE
Syntax docs

### ISSUE THREAD

**Issue by jariji** [JuliaAPlavin/DataPipes.jl#9]
Here are questions that I have while reading the syntax docs

- What goes in the body of an anonymous function created by `_`? eg does `g(f(_))` expand to  `x -> g(f(x))` or `g(x->f(x))`? What about `a + _`, `f(_ + _)`, etc. What are the rules?
- Does inserting `__` mean the previous value doesn't get inserted as the last argument?
- "In nested pipes, use the _ꜛ placeholder to refer to the _ argument of the outer pipe" I thought `__` was the argument of the outer pipe? I don't understand what this means.

**Comment by aplavin** [comment]
> What goes in the body of an anonymous function created by _?

Replacements are always done at the top level. This cleanly avoids ambiguities, and generally feels natural for pipelines.
Added to docs.

> Does inserting __ mean the previous value doesn't get inserted as the last argument?

Indeed, whenever `__` is present, the previous value doesn't get inserted automatically. Added clarification to docs.
Any other reasonable ways you can see it working?

> "In nested pipes, use the _ꜛ placeholder to refer to the _ argument of the outer pipe" I thought __ was the argument of the outer pipe? I don't understand what this means.

Hm... `__` is the previous argument of the _current_ pipe, while `_ꜛ` refers to the outer pipe whenever nesting is present.
Note that this is described in the "very rarely needed and can be safely ignored" section :) I don't personally use `_ꜛ` anywhere regularly, maybe it shouldn't be used at all – preferring more explicit notations in complex cases for clarity.

**Comment by aplavin** [comment]
Thanks for raising these questions, I updated the docs following them!

**Comment by jariji** [comment]
Sounds good, cheers!
